components:
  schemas:
    system-version:
      type: object
      properties:
        version:
          type: string
          description: Version of the REST API software
        attackSpecVersion:
          type: string
          description: ATT&CK spec version of the REST API software

    allowed-values:
      type: object
      properties:
        objectType:
          type: string
          example: 'technique'
        properties:
          $ref: '#/components/schemas/allowedValuesForProperty'

    allowedValuesForProperty:
      type: array
      items:
        type: object
        properties:
          propertyName:
            type: string
            example: 'x_mitre_platforms'
          domains:
            $ref: '#/components/schemas/allowedValuesForDomain'

    allowedValuesForDomain:
      type: array
      items:
        type: object
        properties:
          domainName:
            type: string
            example: 'enterprise-attack'
          allowedValues:
            type: array
            items:
              type: string
              example: 'Linux'

    organization-identity:
      type: object
      properties:
        id:
          type: string
          example: 'identity--76abfbed-a92f-4e2a-953e-dc83f90ecddc'

    authn-mechanism:
      type: object
      properties:
        authnType:
          type: string
          example: 'oidc'

    default-marking-definition-ids:
      type: array
      items:
        type: string
        example: 'marking-definition--a0262641-9222-4e26-b5f5-f44c59fb3230'

    organization-namespace:
      type: object
      properties:
        range_start:
          type: number
          example: 4000
        prefix:
          type: string
          example: 'MYORG'
