components:
  schemas:
    allowed-values:
      type: object
      properties:
        objectType:
          type: string
          example: 'technique'
        properties:
          $ref: '#/components/schemas/allowedValuesForProperty'

    allowedValuesForProperty:
      type: array
      items:
        type: object
        properties:
          propertyName:
            type: string
            example: 'x_mitre_platforms'
          domains:
            $ref: '#/components/schemas/allowedValuesForDomain'

    allowedValuesForDomain:
      type: array
      items:
        type: object
        properties:
          domainName:
            type: string
            example: 'enterprise-attack'
          allowedValues:
            type: array
            items:
              type: string
              example: 'Linux'

    organization-identity:
      type: object
      properties:
        id:
          type: string
          example: 'identity--76abfbed-a92f-4e2a-953e-dc83f90ecddc'

    authn-mechanism:
      type: object
      properties:
        mechanism:
          type: string
          example: 'oidc'
