paths:
  /api/config/system-version:
    get:
      summary: 'Get the system version info'
      operationId: 'config-get-system-version'
      description: |
        This endpoint gets the system version info from the package.json file.
      tags:
        - 'System Configuration'
      responses:
        '200':
          description: 'System version info'
          content:
            application/json:
              schema:
                $ref: '../components/system-configuration.yml#/components/schemas/system-version'

  /api/config/allowed-values:
    get:
      summary: 'Get the list of domain-specific allowed values'
      operationId: 'config-get-allowed-values'
      description: |
        This endpoint gets a list of domain-specific allowed values for certain properties.
      tags:
        - 'System Configuration'
      responses:
        '200':
          description: 'A list of allowed values.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../components/system-configuration.yml#/components/schemas/allowed-values'

  /api/config/organization-identity:
    get:
      summary: 'Get the designated organization identity'
      operationId: 'config-get-organization-identity'
      description: |
        This endpoint gets the organization identity object for the system.
      tags:
        - 'System Configuration'
      responses:
        '200':
          description: 'An identity object.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../components/identities.yml#/components/schemas/identity'
    post:
      summary: 'Set the designated organization identity'
      operationId: 'config-set-organization-identity'
      description: |
        This endpoint sets the organization identity for the system.
        The identity object must already exist.
      tags:
        - 'System Configuration'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../components/system-configuration.yml#/components/schemas/organization-identity'
      responses:
        '204':
          description: 'The organization identity has been successfully set.'
        '400':
          description: 'Missing or invalid parameters were provided. The organization identity was not set.'
        '404':
          description: 'The identity could not be found. The organization identity was not set.'

  /api/config/authn:
    get:
      summary: 'Get information describing the available user authentication mechanisms'
      operationId: 'config-get-authn'
      description: |
        This endpoint gets information describing the available user authentication mechanisms.
        This is intended to be used by the client to determine which authentication mechanisms are available to be used and does not require the user to be logged in.
      tags:
        - 'System Configuration'
      responses:
        '200':
          description: 'A list of available authentication mechanisms.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../components/system-configuration.yml#/components/schemas/authn-mechanism'

  /api/config/default-marking-definitions:
    get:
      summary: 'Get the default marking definitions'
      operationId: 'config-get-default-marking-definitions'
      description: |
        This endpoint gets the default marking definition objects for the system.
      tags:
        - 'System Configuration'
      parameters:
        - name: refOnly
          in: query
          description: |
            Only return the STIX ID of the default marking definitions instead of the objects.
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: 'An array of marking definition objects.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../components/marking-definitions.yml#/components/schemas/marking-definition'
    post:
      summary: 'Set the default marking definitions'
      operationId: 'config-set-default-marking-definitions'
      description: |
        This endpoint sets the default marking definitions for the system.
        The marking definitions must already exist.
      tags:
        - 'System Configuration'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../components/system-configuration.yml#/components/schemas/default-marking-definition-ids'
      responses:
        '204':
          description: 'The default marking definitions have been successfully set.'
        '400':
          description: 'Missing or invalid parameters were provided. The default marking definitions were not set.'
        '404':
          description: 'A marking definition could not be found. The default marking definitions were not set.'

  /api/config/organization-namespace:
    get:
      summary: 'Get the designated organization namespace'
      operationId: 'config-get-organization-namespace'
      description: |
        This endpoint gets the organization namespace definition (if any) defined for the system.
      tags:
        - 'System Configuration'
      responses:
        '200':
          description: 'A namespace object.'
          content:
            application/json:
              schema:
                $ref: '../components/system-configuration.yml#/components/schemas/organization-namespace'
    post:
      summary: 'Set the designated organization namespace'
      operationId: 'config-set-organization-namespace'
      description: |
        This endpoint sets the organization namespace for the system.
      tags:
        - 'System Configuration'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../components/system-configuration.yml#/components/schemas/organization-namespace'
      responses:
        '204':
          description: 'The organization namespace has been successfully set.'
        '400':
          description: 'Missing or invalid parameters were provided. The organization namespace was not set.'
