openapi: '3.0.3'
info:
  title: 'ATT&CK Workbench REST API'
  version: '0.0.1'
servers:
  - url: '{protocol}://{hostname}:{port}/'
    variables:
      protocol:
        default: 'http'
      hostname:
        default: 'localhost'
      port:
        default: '3000'
tags:
  - name: 'ATT&CK Objects'
    description: 'Operations on all ATT&CK objects'
  - name: 'Techniques'
    description: 'Operations on techniques'
  - name: 'Tactics'
    description: 'Operations on tactics'
  - name: 'Groups'
    description: 'Operations on groups'
  - name: 'Software'
    description: 'Operations on software (tools and malware)'
  - name: 'Mitigations'
    description: 'Operations on mitigations'
  - name: 'Matrices'
    description: 'Operations on matrices'
  - name: 'Identities'
    description: 'Operations on identities'
  - name: 'Marking Definitions'
    description: 'Operations on marking definitions'
  - name: 'Relationships'
    description: 'Operations on relationships'
  - name: 'Collection Indexes'
    description: 'Operations on collection indexes'
  - name: 'Collections'
    description: 'Operations on collections'
  - name: 'Collection Bundles'
    description: 'Operations on collection bundles'
  - name: 'System Configuration'
    description: 'Operations on the system configuration'

paths:
  # ATT&CK Objects
  /api/attack-objects:
    $ref: 'paths/attack-objects-paths.yml#/paths/~1api~1attack-objects'

  # Techniques
  /api/techniques:
    $ref: 'paths/techniques-paths.yml#/paths/~1api~1techniques'

  /api/techniques/{stixId}:
    $ref: 'paths/techniques-paths.yml#/paths/~1api~1techniques~1{stixId}'

  /api/techniques/{stixId}/modified/{modified}:
    $ref: 'paths/techniques-paths.yml#/paths/~1api~1techniques~1{stixId}~1modified~1{modified}'

  # Tactics
  /api/tactics:
    $ref: 'paths/tactics-paths.yml#/paths/~1api~1tactics'

  /api/tactics/{stixId}:
    $ref: 'paths/tactics-paths.yml#/paths/~1api~1tactics~1{stixId}'

  /api/tactics/{stixId}/modified/{modified}:
    $ref: 'paths/tactics-paths.yml#/paths/~1api~1tactics~1{stixId}~1modified~1{modified}'

  # Groups
  /api/groups:
    $ref: 'paths/groups-paths.yml#/paths/~1api~1groups'

  /api/groups/{stixId}:
    $ref: 'paths/groups-paths.yml#/paths/~1api~1groups~1{stixId}'

  /api/groups/{stixId}/modified/{modified}:
    $ref: 'paths/groups-paths.yml#/paths/~1api~1groups~1{stixId}~1modified~1{modified}'

  # Matrices
  /api/matrices:
    $ref: 'paths/matrices-paths.yml#/paths/~1api~1matrices'

  /api/matrices/{stixId}:
    $ref: 'paths/matrices-paths.yml#/paths/~1api~1matrices~1{stixId}'

  /api/matrices/{stixId}/modified/{modified}:
    $ref: 'paths/matrices-paths.yml#/paths/~1api~1matrices~1{stixId}~1modified~1{modified}'

  # Identities
  /api/identities:
    $ref: 'paths/identities-paths.yml#/paths/~1api~1identities'

  /api/identities/{stixId}:
    $ref: 'paths/identities-paths.yml#/paths/~1api~1identities~1{stixId}'

  /api/identities/{stixId}/modified/{modified}:
    $ref: 'paths/identities-paths.yml#/paths/~1api~1identities~1{stixId}~1modified~1{modified}'

  # Marking Definitions
  /api/marking-definitions:
    $ref: 'paths/marking-definitions-paths.yml#/paths/~1api~1marking-definitions'

  /api/marking-definitions/{stixId}:
    $ref: 'paths/marking-definitions-paths.yml#/paths/~1api~1marking-definitions~1{stixId}'

  # Software
  /api/software:
    $ref: 'paths/software-paths.yml#/paths/~1api~1software'

  /api/software/{stixId}:
    $ref: 'paths/software-paths.yml#/paths/~1api~1software~1{stixId}'

  /api/software/{stixId}/modified/{modified}:
    $ref: 'paths/software-paths.yml#/paths/~1api~1software~1{stixId}~1modified~1{modified}'

  # Mitigations
  /api/mitigations:
    $ref: 'paths/mitigations-paths.yml#/paths/~1api~1mitigations'

  /api/mitigations/{stixId}:
    $ref: 'paths/mitigations-paths.yml#/paths/~1api~1mitigations~1{stixId}'

  /api/mitigations/{stixId}/modified/{modified}:
    $ref: 'paths/mitigations-paths.yml#/paths/~1api~1mitigations~1{stixId}~1modified~1{modified}'

  # Relationships
  /api/relationships:
    $ref: 'paths/relationships-paths.yml#/paths/~1api~1relationships'

  /api/relationships/{stixId}:
    $ref: 'paths/relationships-paths.yml#/paths/~1api~1relationships~1{stixId}'

  /api/relationships/{stixId}/modified/{modified}:
    $ref: 'paths/relationships-paths.yml#/paths/~1api~1relationships~1{stixId}~1modified~1{modified}'

  # Collection Indexes
  /api/collection-indexes:
    $ref: 'paths/collection-indexes-paths.yml#/paths/~1api~1collection-indexes'

  /api/collection-indexes/{id}:
    $ref: 'paths/collection-indexes-paths.yml#/paths/~1api~1collection-indexes~1{id}'

  # Collections
  /api/collections:
    $ref: 'paths/collections-paths.yml#/paths/~1api~1collections'

  /api/collections/{stixId}:
    $ref: 'paths/collections-paths.yml#/paths/~1api~1collections~1{stixId}'

  # Collection Bundles
  /api/collection-bundles:
    $ref: 'paths/collection-bundles-paths.yml#/paths/~1api~1collection-bundles'

  # System Configuration
  /api/config/allowed-values:
    $ref: 'paths/system-configuration-paths.yml#/paths/~1api~1config~1allowed-values'
