openapi: '3.0.3'
info:
  title: 'ATT&CK Workbench REST API'
  version: '0.0.1'
servers:
  - url: '{protocol}://{hostname}:{port}/'
    variables:
      protocol:
        default: 'http'
      hostname:
        default: 'localhost'
      port:
        default: '3000'
tags:
  - name: 'Techniques'
    description: 'Operations on techniques.'
  - name: 'Groups'
    description: 'Operations on groups.'
paths:
  /api/techniques:
    get:
      summary: 'Get a list of techniques'
      operationId: 'technique-get-all'
      description: |
        This endpoint gets a list of techniques from the workspace.
        The list of techniques may include multiple versions of each technique.
      tags:
        - 'Techniques'
      responses:
        '200':
          description: 'A list of techniques.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/technique'

    post:
      summary: 'Create a technique'
      operationId: 'technique-create'
      description: |
        This endpoint creates a new technique in the workspace.
        If the `stix.id` property is set, it creates a new version of an existing technique.
        If the `stix.id` property is not set, it creates a new technique, generating a STIX id for it.
      tags:
        - 'Techniques'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/technique'
      responses:
        '201':
          description: 'The technique has been successfully created.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/technique'
        '400':
          description: 'Missing or invalid parameters were provided. The technique was not created.'
        '409':
          description: 'Duplicate `stix.id` and `stix.modified` properties. The technique was not created.'

  /api/techniques/{stixId}:
    get:
      summary: 'Get one or more versions of a technique'
      operationId: 'technique-get-one-id'
      description: |
        This endpoint gets a list of one or more versions of a technique from the workspace, identified by their STIX id.
      tags:
        - 'Techniques'
      parameters:
        - name: stixId
          in: path
          description: 'STIX id of the technique to retrieve'
          required: true
          schema:
            type: string
        - name: versions
          in: query
          description: |
            The versions of the technique to retrieve.
            `all` gets all versions of the technique, `latest` gets only the latest version.
          schema:
            type: string
            enum:
              - all
              - latest
            default: latest
      responses:
        '200':
          description: 'A list of techniques matching the requested STIX id.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/technique'

  /api/techniques/{stixId}/modified/{modified}:
    get:
      summary: 'Gets the version of a technique matching the STIX id and modified date'
      operationId: 'technique-get-by-id-and-modified'
      description: |
        This endpoint gets a single version of a technique from the workspace, identified by its STIX id and modified date.
      tags:
        - 'Techniques'
      parameters:
        - name: stixId
          in: path
          description: 'STIX id of the technique to retrieve'
          required: true
          schema:
            type: string
        - name: modified
          in: path
          description: 'modified date of the technique to retrieve'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'The version of a technique matching the STIX id and modified date.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/technique'
        '404':
          description: 'A technique with the requested STIX id and modified date was not found.'
    put:
      summary: 'Update a technique'
      operationId: 'technique-update'
      description: |
        This endpoint updates a single version of a technique in the workspace, identified by its STIX id and modified date.
      tags:
        - 'Techniques'
      parameters:
        - name: stixId
          in: path
          description: 'STIX id of the technique to update'
          required: true
          schema:
            type: string
        - name: modified
          in: path
          description: 'modified date of the technique to update'
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/technique'
      responses:
        '200':
          description: 'The technique was updated.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/technique'
        '400':
          description: 'Missing or invalid parameters were provided. The technique was not updated.'
        '404':
          description: 'A technique with the requested STIX id and modified date was not found.'
    delete:
      summary: 'Delete a technique'
      operationId: 'technique-delete'
      description: |
        This endpoint deletes a single version of a technique from the workspace.
        The technique is identified by its STIX id and modified date.
      tags:
        - 'Techniques'
      parameters:
        - name: stixId
          in: path
          description: 'STIX id of the technique to delete'
          required: true
          schema:
            type: string
        - name: modified
          in: path
          description: 'modified date of the technique to delete'
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 'The technique was successfully deleted.'
        '404':
          description: 'A technique with the requested STIX id and modified date was not found.'

components:
  schemas:
    workspace:
      type: object
      required:
        - domains
      properties:
        # STIX common properties
        domains:
          type: array
          description: 'This property replaces x_mitre_collections'
          items:
            type: string
            example: 'attack-enterprise'

    stix-common:
      type: object
      required:
        - type
        - spec_version
        - created
        - modified
      properties:
        # STIX common properties
        type:
          type: string
          pattern: '^attack-pattern$'
          example: 'attack-pattern'
        spec_version:
          type: string
          pattern: '^2.1$'
          example: '2.1'
        id:
          type: string
          example: 'attack-pattern--76abfbed-a92f-4e2a-953e-dc83f90ecddc'
        created:
          type: string
          format: date-time
        modified:
          type: string
          format: date-time
        created_by_ref:
          type: string
          example: 'identity--6444f546-6900-4456-b3b1-015c88d70dab'
        revoked:
          type: boolean
          example: false
        external_references:
          type: array
          items:
            $ref: '#/components/schemas/external_reference'
        object_marking_refs:
          type: array
          items:
            type: string
            example: 'marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168'

    technique:
      type: object
      required:
        - workspace
        - stix
      properties:
        workspace:
          $ref: '#/components/schemas/workspace'
        stix:
          $ref: '#/components/schemas/stix-attack-pattern'

    stix-attack-pattern:
      allOf:
        - $ref: '#/components/schemas/stix-common'
        - type: object
          required:
            - name
          properties:
            # attack-pattern specific properties
            name:
              type: string
              example: 'AppInit DLLs'
            description:
              type: string
            kill_chain_phases:
              type: array
              items:
                $ref: '#/components/schemas/kill_chain_phase'
            # ATT&CK custom properties
            x_mitre_contributors:
              type: array
              items:
                type: string
            x_mitre_data_sources:
              type: array
              items:
                type: string
            x_mitre_deprecated:
              type: boolean
              example: false
            x_mitre_detection:
              type: string
            x_mitre_effective_permissions:
              type: array
              items:
                type: string
                example: 'Administrator'
            x_mitre_permissions_required:
              type: array
              items:
                type: string
                example: 'Administrator'
            x_mitre_platforms:
              type: array
              items:
                type: string
                example: 'Windows'
            x_mitre_subtechnique:
              type: boolean
              example: false
            x_mitre_system_requirements:
              type: array
              items:
                type: string
            x_mitre_version:
              type: string
              example: '1.0'

    editor_identity:
      type: object
      description: 'This property replaces mitreId'
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name

    external_reference:
      type: object
      properties:
        source_name:
          type: string
          example: 'mitre-attack'
        description:
          type: string
        url:
          type: string
          example: 'https://attack.mitre.org/techniques/T1103'
        external_id:
          type: string
          example: 'T1103'
      required:
        - source_name

    kill_chain_phase:
      type: object
      properties:
        kill_chain_name:
          type: string
        phase_name:
          type: string
      required:
        - kill_chain_name
        - phase_name
