name: run static checks

on: [push]

jobs:
  build:
    name: static-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run lint
      - run: npm run snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
