name: publish

on:
  push:
    branches: [master, develop]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          echo $CR_PAT | docker login ghcr.io -u center-for-threat-informed-defense --password-stdin
          docker build . --tag ghcr.io/center-for-threat-informed-defense/attack-workbench-rest-api:latest
          docker push ghcr.io/center-for-threat-informed-defense/attack-workbench-rest-api:latest
        env:
          CR_PAT: ${{ secrets.CR_PAT }}